apiVersion: v1
kind: ConfigMap
metadata:
  name: db-env
data:
  DB_USERNAME: "postgres"
  DB_NAME: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
    DB_PASSWORD: "63pZQd8RiO"